### ISSUE TITLE
Preview Menu Customization

### ISSUE THREAD

**Issue by imWillX** [imWillX/CrateReloaded#129]

**Comment by imWillX** [comment]
Config.yml
```YML
preview-menu:
    next-button: '262 1 &aNext_Page &eClick_to_enter_the_next_page.'
    close-button: '355 1 &4&lGo_back! &7Return_to_the_crate_selector!'
    back-button: '355 1 &4&lGo_back! &7Return_to_the_crate_selector!'
```
