### ISSUE TITLE
Animation Type

### ISSUE THREAD

**Issue by imWillX** [imWillX/CrateReloaded#152]
**Animation Config Value** 1.3.97.8
We're adding in a config key to change animations. This will give more flexibility and consistency.

This is currently available with only crates with type, `keycrate` or `mysterycrate`.
Valid Animations: `ROULETTE`, `CSGO`
**Normal crate with animation**
```
MysteryCrate:
    type: MYSTERYCRATE
    animation: 'CSGO'
    ...

```
**Key with no animations**
```
FoodieKey:
    type: KEYCRATE
    animation: 'none'
    ...
```
**Key with roulette**
```
RouletteKey:
    type: KEYCRATE
    animation: "ROULETTE"
    ...
```
**Key with csgo**
```
CSGOKey:
    type: KEYCRATE
    animation: 'CSGO'
    ...
```
