### ISSUE TITLE
Hologram display height offset.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#68]
Spigot 1.10
CrateReloaded Premium 1.3.73
HolographicDisplays 2.2 

HolographicDisplays hook seems to display a bit high. Y offset by 1 or so?

![link](http://i.imgur.com/qPTGXHw.png)
![link2](http://i.imgur.com/sWOrlfd.png)

**Comment by imWillX** [comment]
Add a global holographic offset. Will be included in next update.
```
# Config.yml
# Holographic Offset
#
holographic-offset:
    x: 0.0
    y: -0.3
    z: 0.0
```
